-- ── Tables ───────────────────────────────────────────────────────────────────

-- 1. baby_events: All activity logs
DROP TABLE IF EXISTS public.baby_events;
CREATE TABLE public.baby_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    end_time   TIMESTAMPTZ,
    type       TEXT NOT NULL CHECK (type IN ('top', 'mom_l', 'mom_r', 'diaper')),
    amount_ml  NUMERIC,
    pee_amount  TEXT,
    poop_amount TEXT CHECK (poop_amount IN ('none', 'light', 'heavy')),
    is_diaper_free BOOLEAN DEFAULT FALSE,
    notes      TEXT
);

-- Ensure only one active feed can exist at a time (race-condition protection)
CREATE UNIQUE INDEX only_one_active_feed 
ON public.baby_events ((1)) 
WHERE end_time IS NULL AND type IN ('mom_l', 'mom_r', 'top');

-- 2. ai_insights: Single row for dashboard context
DROP TABLE IF EXISTS public.ai_insights;
CREATE TABLE public.ai_insights (
    id          BIGINT PRIMARY KEY DEFAULT 1,
    strip_json  JSONB DEFAULT '{}',
    micro_json  JSONB DEFAULT '{}',
    updated_at  TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT  single_row CHECK (id = 1)
);

-- ── Security & RLS ───────────────────────────────────────────────────────────

ALTER TABLE public.baby_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ai_insights ENABLE ROW LEVEL SECURITY;

-- baby_events Policies
CREATE POLICY "Enable read access for all users" ON public.baby_events FOR SELECT USING (true);
CREATE POLICY "Enable insert for all users" ON public.baby_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for all users" ON public.baby_events FOR UPDATE USING (true) WITH CHECK (true);

-- ai_insights Policies
CREATE POLICY "Enable read access for all users" ON public.ai_insights FOR SELECT USING (true);
CREATE POLICY "Enable update for service role" ON public.ai_insights FOR UPDATE USING (true);

-- ── Realtime ─────────────────────────────────────────────────────────────────

ALTER PUBLICATION supabase_realtime ADD TABLE public.baby_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.ai_insights;
